name: colorize
version: 2.0.0
description: Colorize console output
author: Alexey Salnikov <me@iamsalnikov.ru>
homepage: https://github.com/iamsalnikov/colorize
environment:
  sdk: '>=2.0.0 <3.0.0'
dependencies:

dev_dependencies:
#  unittest: any
